name: flutter_notebook_chapter_53
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  percent_indicator: ^4.2.5
  hugeicons: ^1.1.7
  easy_pie_chart: ^1.0.2
  smooth_page_indicator:
  gap:
  material_ui: ^1.1.0
  dotted_border: ^3.1.0
  avatar_stack: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
